# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wolfpay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=255)),
                ('op', models.TextField()),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wolfpay.Shop')),
            ],
        ),
    ]
