# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wolfpay', '0003_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('addr', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('op', models.TextField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wolfpay.Product')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wolfpay.Shop')),
            ],
        ),
    ]
