# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolfpay', '0006_transaction_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receive',
            field=models.FloatField(null=True),
        ),
    ]
