# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wolfpay', '0007_transaction_receive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True)),
                ('addr', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wolfpay.Shop')),
            ],
        ),
    ]
