# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolfpay', '0008_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
