# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 17:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolfpay', '0009_auto_20180211_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='send',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 2, 11, 17, 40, 25, 679000)),
            preserve_default=False,
        ),
    ]
